apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sy-rds-secret-provider
  namespace: default
spec:
  provider: aws
#  secretObjects:
#    - secretName: sy-secret
#      type: Opaque
#      data:
#        - objectName: spring.datasource.username
#          key: spring.datasource.username
#        - objectName: spring.datasource.password
#          key: spring.datasource.password
#        - objectName: kis.api.appKey
#          key: kis.api.appKey
#        - objectName: kis.api.appSecret
#          key: kis.api.appSecret
#        - objectName: slack_web_hook_url
#          key: slack_web_hook_url
#      labels:
#        managed-by: secrets-store-csi
#      annotations:
#        kubernetes.io/service-account.name: "sy-secret-sa"
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:ap-northeast-2:128945985183:secret:sy-secretsmanager-PTar8k"
#        jmesPath:
#          - path: rds_username
#            objectAlias: spring.datasource.username
#          - path: rds_password
#            objectAlias: spring.datasource.password
#          - path: kis_app_key
#            objectAlias: kis.api.appKey
#          - path: kis_app_secret
#            objectAlias: kis.api.appSecret
#          - path: slack_web_hook_url
#            objectAlias: slack.web-hook-url